// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbu5a9d_mRxx_ZkMZ0nRy9CUX-Euu-IbM',
    appId: '1:23880765638:web:45217e09fed22a4b28c7c7',
    messagingSenderId: '23880765638',
    projectId: 'flutter-task-16ddb',
    authDomain: 'flutter-task-16ddb.firebaseapp.com',
    storageBucket: 'flutter-task-16ddb.firebasestorage.app',
    measurementId: 'G-1BSPD1HK7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2B4T10KJnssV9sIQ3JXSVobJrOdStOqY',
    appId: '1:23880765638:android:5e9e675a6f311e8128c7c7',
    messagingSenderId: '23880765638',
    projectId: 'flutter-task-16ddb',
    storageBucket: 'flutter-task-16ddb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANy1IPNL1smhavbTKy5pqQFNo7t3JFbwA',
    appId: '1:23880765638:ios:4e16e680e8995ca228c7c7',
    messagingSenderId: '23880765638',
    projectId: 'flutter-task-16ddb',
    storageBucket: 'flutter-task-16ddb.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANy1IPNL1smhavbTKy5pqQFNo7t3JFbwA',
    appId: '1:23880765638:ios:4e16e680e8995ca228c7c7',
    messagingSenderId: '23880765638',
    projectId: 'flutter-task-16ddb',
    storageBucket: 'flutter-task-16ddb.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbu5a9d_mRxx_ZkMZ0nRy9CUX-Euu-IbM',
    appId: '1:23880765638:web:9eb82afde5f53c4528c7c7',
    messagingSenderId: '23880765638',
    projectId: 'flutter-task-16ddb',
    authDomain: 'flutter-task-16ddb.firebaseapp.com',
    storageBucket: 'flutter-task-16ddb.firebasestorage.app',
    measurementId: 'G-EEN4ECSXCJ',
  );

}